nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    NODE_TLS_REJECT_UNAUTHORIZED: 0
    S2S_SECRET: ${S2S_SECRET}
    IDAM_SECRET: ${IDAM_SECRET}
    IDAM_API_SERVICE: https://idam-api.aat.platform.hmcts.net
    IDAM_WEB_SERVICE: https://idam-web-public.aat.platform.hmcts.net
    APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
    FEATURE_SECURE_COOKIE_ENABLED: false

    # deprecate
    PUI_ENV: preview
    NODE_CONFIG_ENV: prod
